spring:
  datasource:
    continue-on-error: false
    name: drug_manager
    generate-unique-name: false
    url: jdbc:mariadb://localhost:3306/drug_manager
    username: MHC
    password: yousql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    sql-script-encoding: UTF-8
    separator: ;
    druid:
      name: drug_manager
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 40000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      use-global-data-source-stat: true
      stat-view-servlet:
        enabled: true
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 500
          merge-sql: true
        slf4j:
          enabled: true
  mvc:
#    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false
  thymeleaf:
    encoding: UTF-8
    cache: false
  cache:
    type: redis
logging:
  level:
    root: warn
    org.mybatis: info
    tk.mybatis: info
    top.codermhc.drugmanager: info
    org.springframework.cache: info
#    org.apache.shiro: trace
    org.crazycake.shiro: trace
server:
  port: 8090
  error:
    whitelabel:
      enabled: false

shiro-redis:
  redis-manager:
    host: localhost:6379
